name: Health Check

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  health-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check deployed app is live
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstack-osa-11.onrender.com/health
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
