name: Health Check

on:
  push:
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check deployed app is live
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstack-osa-11.onrender.com/health
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
